### ISSUE TITLE
Panakeia.py: FileNotFoundError

### ISSUE THREAD

**Issue by nicola-palmieri** [BioSina/Panakeia#4]
Hello

I have started testing Panakeia on a set of 59 Ornithobacterium isolates. Here is my protocol:

- Prepare folder with gff files: gff-files-59isolates
- Prepare folder with fasta proteins: fasta-proteins-59isolates
- Rename ORT-UMN_88 to ORT_UMN_88 since dash might create problems in the Panakeia pipeline

- Concatenate all protein sequences
cat fasta-proteins-59isolates/*faa > fasta-proteins-59isolates.fasta

cd panakeia-output
python ../Panakeia/PangenomeAnalysis/Clustering.py ../fasta-proteins-59isolates.fasta 59
python ../Panakeia/PangenomeAnalysis/Panakeia.py output ../gff-files-59isolates protein_clusters.txt representative_seq.faa

The Panakeia.py scripts reads the strains correctly, but generates an error at the Read GFFs step:

> Read GFFs!
> Traceback (most recent call last):
>   File "/Volumes/Data3/2023/ORT/run1+2/10-panakeia/panakeia-output/../Panakeia/PangenomeAnalysis/Panakeia.py", line 786, in <module>
>     main()
>   File "/Volumes/Data3/2023/ORT/run1+2/10-panakeia/panakeia-output/../Panakeia/PangenomeAnalysis/Panakeia.py", line 772, in main
>     draw_clusters()
>   File "/Volumes/Data3/2023/ORT/run1+2/10-panakeia/panakeia-output/../Panakeia/PangenomeAnalysis/Panakeia.py", line 701, in draw_clusters
>     draw_genomes()
>   File "/Volumes/Data3/2023/ORT/run1+2/10-panakeia/panakeia-output/../Panakeia/PangenomeAnalysis/Panakeia.py", line 758, in draw_genomes
>     nx.write_graphml(straingraph, args.output+"/"+"strain_"+s+".graphML")
>   File "/Users/nicola.palmieri/opt/miniconda3/lib/python3.9/site-packages/networkx/utils/decorators.py", line 766, in func
>     return argmap._lazy_compile(__wrapper)(*args, **kwargs)
>   File "<class 'networkx.utils.decorators.argmap'> compilation 5", line 3, in argmap_write_graphml_lxml_1
>   File "/Users/nicola.palmieri/opt/miniconda3/lib/python3.9/site-packages/networkx/utils/decorators.py", line 189, in _open_file
>     fobj = _dispatch_dict[ext](path, mode=mode)
> FileNotFoundError: [Errno 2] No such file or directory: 'output/strain_ORT_UMN_88.graphML'
>

**Comment by bharat1912** [comment]
Hi Nicola-Palmieri
The error is because Panakeia.py does not create the output dir "outfile" to which the analysis files will be written to. You will need to mkdir  outfile (or any other dir of your choice) and include the path to the dir in your CLi.

**Comment by nicola-palmieri** [comment]
Thanks a lot! That solved the problem!
